### ISSUE TITLE
Connect the front end and back end

### ISSUE THREAD

**Issue by hannliu** [WildWindXY/iKunnect#27]
Summary
As part of our ongoing development, we need to establish a connection between our front-end application and the back-end services. This integration is critical for enabling seamless communication and data exchange between the two parts of our application.

Objectives
Establish API Endpoints: Identify and set up the necessary API endpoints on the back end that the front end will interact with.
Data Exchange Format: Define and standardize the format for data exchange (e.g., JSON) between the front end and back end.
Front-End Service Integration: Implement service calls on the front end to interact with the back-end APIs.
Error Handling and Feedback: Ensure robust error handling and user feedback mechanisms for network requests.
Key Areas for Integration
User Authentication: Connect the login/signup interfaces with the user authentication services on the back end.

Data Retrieval and Management: Integrate the interfaces responsible for displaying and managing data (e.g., user profiles, settings) with corresponding back-end services.

Real-time Data Interactions: For dynamic components like chat or live updates, set up appropriate WebSockets or long-polling mechanisms.

Challenges to Address
Security: Secure handling of sensitive data and implementation of authorization and authentication checks.
Performance: Efficient handling of requests to ensure a responsive user experience.
Consistency: Data format and API contract consistency between front end and back end.

Steps for Completion
API Design and Documentation: Collaborate with the back-end team to define API contracts.
Front-End Implementation: Develop the necessary service calls and state management on the front end.
Testing and Validation: Test the integrated system thoroughly to ensure functionality and performance.
Iterative Improvements: Based on testing feedback, iterate over the integration to refine and optimize.

Collaboration
This task requires close collaboration between front-end and back-end teams. Regular communication and updates are essential for the timely and effective completion of this integration.

**Comment by WildWindXY** [comment]
Signup related: A successful signup response from server implies a successful login. This reduces actions performed by the user.
